# Generated by Django 2.2.4 on 2019-08-07 01:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='BathroomSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('type_of_bathroom', models.CharField(max_length=4)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom_sessions', to='home.Dog')),
            ],
        ),
    ]
