# Generated by Django 2.2.4 on 2019-08-07 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190806_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroombreak',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom_breaks', to='home.Dog'),
        ),
        migrations.AlterField(
            model_name='bathroombreak',
            name='type_of_bathroom',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=6),
        ),
    ]
