# Generated by Django 2.2.4 on 2019-08-08 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190806_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroombreak',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
