# Generated by Django 2.2.4 on 2019-08-08 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190807_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroombreak',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
