# Generated by Django 2.2.4 on 2019-08-10 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190807_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='bathroombreak',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='home.Person'),
        ),
    ]
